USE [master]
GO

/****** Object:  Database [Bookkeep]    Script Date: 24/6/2018 2:17:00 PM ******/
CREATE DATABASE [Bookkeep]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Bookkeep', FILENAME = N'E:\Database\Bookkeep.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Bookkeep_log', FILENAME = N'E:\Database\Bookkeep_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Bookkeep] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Bookkeep].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Bookkeep] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Bookkeep] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Bookkeep] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Bookkeep] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Bookkeep] SET ARITHABORT OFF 
GO

ALTER DATABASE [Bookkeep] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Bookkeep] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Bookkeep] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Bookkeep] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Bookkeep] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Bookkeep] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Bookkeep] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Bookkeep] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Bookkeep] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Bookkeep] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Bookkeep] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Bookkeep] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Bookkeep] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Bookkeep] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Bookkeep] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Bookkeep] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Bookkeep] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Bookkeep] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Bookkeep] SET  MULTI_USER 
GO

ALTER DATABASE [Bookkeep] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Bookkeep] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Bookkeep] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Bookkeep] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Bookkeep] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Bookkeep] SET QUERY_STORE = OFF
GO

USE [Bookkeep]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Bookkeep] SET  READ_WRITE 
GO

USE [Bookkeep]
GO
/****** Object:  Table [dbo].[Account]    Script Date: 24/6/2018 2:18:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Account](
	[sAccountCode] [nvarchar](20) NOT NULL,
	[sAccountType] [nvarchar](2) NOT NULL,
	[sAccountName] [nvarchar](1000) NOT NULL,
 CONSTRAINT [PK_Account] PRIMARY KEY CLUSTERED 
(
	[sAccountCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Company]    Script Date: 24/6/2018 2:18:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Company](
	[sCompanyCode] [nvarchar](5) NOT NULL,
	[sCompanyName] [nvarchar](1000) NOT NULL,
 CONSTRAINT [PK_Company] PRIMARY KEY CLUSTERED 
(
	[sCompanyCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Ledger]    Script Date: 24/6/2018 2:18:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ledger](
	[sLedgerId] [nvarchar](50) NOT NULL,
	[sCompanyCode] [nvarchar](5) NOT NULL,
	[sLedgerDocu] [nvarchar](50) NOT NULL,
	[dtLedgerDate] [datetime] NOT NULL,
	[sLedgerDesc] [nvarchar](1000) NULL,
	[sLedgerRef] [nvarchar](1000) NULL,
	[dtReconDate] [datetime] NULL,
 CONSTRAINT [PK_Ledger] PRIMARY KEY CLUSTERED 
(
	[sLedgerId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [IX_Ledger] UNIQUE NONCLUSTERED 
(
	[sCompanyCode] ASC,
	[sLedgerDocu] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LedgerDtl]    Script Date: 24/6/2018 2:18:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LedgerDtl](
	[sLedgerId] [nvarchar](50) NOT NULL,
	[sAccountCode] [nvarchar](20) NOT NULL,
	[sLedgerDescription] [nvarchar](1000) NULL,
	[nLedgerDebit] [numeric](18, 2) NOT NULL,
	[nLedgerCredit] [numeric](18, 2) NOT NULL,
	[nLedgerAmount] [numeric](18, 2) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LedgerDtl] ADD  CONSTRAINT [DF_LedgerDtl_nLedgerDebit]  DEFAULT ((0)) FOR [nLedgerDebit]
GO
ALTER TABLE [dbo].[LedgerDtl] ADD  CONSTRAINT [DF_LedgerDtl_nLedgerCredit]  DEFAULT ((0)) FOR [nLedgerCredit]
GO
ALTER TABLE [dbo].[LedgerDtl] ADD  CONSTRAINT [DF_LedgerDtl_nLedgerAmount]  DEFAULT ((0)) FOR [nLedgerAmount]
GO
USE [master]
GO
ALTER DATABASE [Bookkeep] SET  READ_WRITE 
GO



